### PR TITLE
Allow consumers of the module to supply their own security group

### PR DESCRIPTION
**Pull request by sacarr**
I like this approach to bastion services.  However, I need to inject the bastion service into a VPC and set of security groups without adding a security group to my VPC.

**Proposed Changes**
When I started working on this PR, I intended only to enable the bastion service to be injected into one of the security groups already managed in my VPC rather than attaching my VPC's security groups to the bastion-service launch configuration.  While working on this, I introduced several other changes to work around situations where terraform apply would report issues with the AWS provider or terraform plan could not predict the value of interpolations.  These included:

1. When running terraform apply, the full-with-public-ip example  reported errors while reading from the availability-zones data source in order to populate availability-zones for the auto-scaling group.  Running terraform apply a second time resolves this situation but this is not acceptable in my CI / CD pipeline.  As availability-zones is an optional parameter to the AWS auto-scaling group resource, only needed for EC2 classic, I removed the availability zone attribute from the ASG and removed the calls to the data source.
2. Alphabetized variables and outputs
3. Modified the load-balancer configuration, switching to autoscaling target group attachment resources, to work around a terraform apply issue similar to the one described above in item one. I encountered this issue while testing how the module behaved when adding / removing whitelist host CIDR blocks
4. Modified the security-group configuration to parameterize creation of the bastion service security group and association of security group rules to the supplied security group.  This modification was a bit convoluted as Terraform complained about local variable interpolations that could not be applied during planning.  It would be simpler if this could be refactored to reference only the id of a supplied security group
5.  Modified the auto-scaling group configuration to use an externally supplied security group and eliminate in-line configuration of target group ARNs.
6.  In the full-with-public-ip example, added an HTTP data source to retrieve the public IP of the server from which Terraform apply is executed and add same to service white-listed CIDR blocks
7. Added a security group resource and rules to the full-with-public-ip example to support tests listed below

**Tests**
While there are a couple of open-source packages for Terraform unit and integration testing, this project does not define a preferred approach.  Therefore the tests I executed were manual, based on the full-with-public-id example, inspection of the AWS console after each test and observation of the output from ssh -v -p 2222 and ssh -v -p 22.  Tests included:

1. Create a bastion service with no white-listed CIDR blocks using the bastion-service supplied security group
1a. Add a white-listed CIDR block to the bastion service
1b. Add a white-listed CIDR block to the bastion host
1c. Removed the white-listed CIDR block from the bastion service
1d. Removed the white-listed CIDR block from the bastion host
1e. Add a white-listed CIDR block to the bastion host
1f.  Add an additional security group to the bastion service launch configuration
1f. Destroy all resources

After each test, I

1. Inspected the load-balancer, load-balancer targets, security group and security group rules using the AWS console and verifying the CIDR blocks, target routing and health-checks were as expected
2. Executed ssh -v -p 22 **BASTION-SERVICE-LB-DNS-NAME** and compared outcome to anticipation based on security group rules
3. While connected to a shell in a bastion-service container, executed ssh -v -p 2222 **BASTION_HOST-PRIVATE-IP** and compared result to anticipation based on security group rules and IAM policy
4. While connected to a shell in a bastion-service container, executed ssh -v -p 2222 **BASTION_HOST-PRIVATE-IP** and compared result to anticipation based on security group rules
5. Executed ssh -v -p 2222 **BASTION-SERVICE-LB-DNS-NAME** and compared outcome to anticipation based on security group rules and IAM policy

All tests were repeated using the VPC, security group and security group rules added to the full-with-public-ip example then again using a VPC and security group infrastructure defined in a separate module.

**Known Limitations**
1. In my testing I was able to attach a security group to the bastion-service launch configuration that did not include any security group rules.  This was actually possible in the original design.  I have not added logic to prevent this scenario. 
2.  This PR disallows use in EC2 classic environments

**Apologies for a rather large PR** I did not anticipate the extent of the changes I would have to make

### CODE REVIEW

**Comment by joshuamkite** [comment]
Thank you for the considerable amount of work you have put into this pull request! There's a great deal to review here and many different aspects are covered. You will forgive me if it takes some time for me to go through and I have some questions along the way.

I do place a high value on consistent behaviour between versions. Whilst new features are welcome, I would generally avoid breaking features that people may already have in production. Having said this, I am not really concerned about supporting EC2 classic environments since these necessarily can only exist in an account created more than (just under) 6 years ago, are deprecated, and I could not test in such an environment anyway.

I am curious as to your rationale for using pre-existing security groups and would like to understand this better. In the design as it is currently, a dedicated security group is created with appropriate rules but it is also possible to attach an arbitrary number of additional security groups. The idea here is to support a large scale enterprise, e.g. where it is convenient to have a security group for whitelisted IP addresses that can be managed separately to the bastion deployment. Because additional security groups can be managed elsewhere, yes, they can be empty- they are exterior to this plan. It is also possible to not specify any external IP addresses and so the bastion cannot be reached from outside of the VPC. Taking the opposite approach, as you have done here, if you are managing only _rules_ within a pre-existing security group with terraform then you risk getting into a difficult situation where a resource, or part of it, is managed by two different terraform plans, or partially by terraform and partially not. What is the gain from your approach that counters this? What is the problem that you are trying to solve?

**Comment by joshuamkite** [comment]
It's now been 7 days since I requested additional information regarding this P/R. Since it is very large and makes significant changes to core functionality for this module I am afraid that I am not able to accept it without more understanding. If you are not able to assist with this within the next two weeks then I regret that I shall have to reject it

**Comment by sacarr** [comment]
My apologies Joshua.  I have been away since I submitted the PR.  I do understand the concern about breaking utility for EC2 classic environments.  Without your understanding of how the service is used, it was not obvious whether anyone running in an EC2 classic environment was a consumer of the service.  I'll think a little more about how to parameterize for EC2 classic but, as I did not see any obvious method to detect EC2 classic when I first created the PR, I don't hold much hope.

I want to inject the bastion service into an existing security group as my use case is a bit different.  I am starting from scratch in a smaller enterprise.  Everything is in Terraform already so I don't need to be concerned about partial management with Terraform.  I already have a security group for management functions with at least one of the same white-list rules the bastion service needs. I am simply trying to limit the number of groups to which I need to maintain visibility as I scale the infrastructure.

Most of the other changes were introduced to work around the issue described in the full-with-external-ip example.  If you are interested in the work-arounds for the example but not the systemic changes, let me know.

**Comment by joshuamkite** [comment]
Welcome back Stephen!

I was perhaps unclear in my previous message- I am **not** too bothered about maintaining compatibility with classic environments. If leaving the current _module_ code is no-cost then I would leave it in but suggest that you create a second `example` plan.

With regard to the security groups- thank you for helping me understand your rationale a little better. If I understand you correctly then you are concerned about (human?) 'visibility' of security groups. I'm sorry but I don't think that your approach here will scale well and I cannot see it as advisable. To give you some context- at my last employer this bastion was deployed into 2-4 regions each across about 200-250 AWS accounts in a single AWS organisation, so somewhere in the order of 700 deployments, just for bastions, not including any of the other deployments. As you can understand, it's simply not practical to review these with awscli commands or in a web console- the important thing is to be able to deploy declaratively and consistently. Terraform _is_ declarative and your approach of _mutating_ resources works against that. This is the sort of approach that is favoured by configuration management tools- which are a quite different thing. As I have already said, I think that you will get into a difficult situation where a security group is managed in part by two different Terraform plans. For example AWS/Terraform won't normally let you delete AWS resources that have dependencies so this means that the security group that you are proposing to mutate will introduce a dependency chain for the modules writing to it. This is not a good idea and circular dependencies can be a real issue. I would suggest you look at tagging your resources instead.

**Comment by sacarr** [comment]
Joshua,
Thanks for the feedback.  I do not have the complexity you describe at your last employer.  Still, I don't think I was clear about my objective as I am not concerned about human visibility.  

Before I found the bastion module, I had a deployment with SSH access from a small number of external IPs, intra-subnet security and health-check rules.  Instead of mutating that configuration, I passed the port I had configured in that deployment for management functions to the bastion module as its health-check port.  I tested then realized I had to pass at least one of the VPC security groups to the bastion module configuration too.  After passing a security group reference, everything worked as expected but the rules for the bastion module were very similar to the rules I had already configured in the VPC module.

I wondered why the bastion module could not simply use the security group reference directly.  I understand the bastion module must control the security group rules it uses but I did not see any obvious reason why it had to control the security group too.  Given the extent to which the bastion module is already configurable,  it seemed a useful exercise to pass a reference to a security group into the bastion module.  Doing so taught me a lot about Terraform.

Your caution about dependencies prompted me to go back and test again.  While bouncing back and forth between internal and reference security group, Terraform failed to destroy the bastion module security group because it was waiting for an instance to shutdown but the health-check rule had already been destroyed.  AWS could not update the state of the instance and Terraform timed out.  There are a couple of similar issues reported on Github where dependencies during creation work as expected but destroying resources exposed dependencies Terraform did not detect.  I added an explicit dependency from the load balancer target group to the security group.  This seems to have fixed the situation.  I will keep testing tomorrow.  

Thank you again for the feedback. IT was food for thought and did prompt me to do some more testing.  If I have done a better job of describing my motivation and you don't disagree with enabling configurability of the security group, I will add a commit to the PR to address the dependency described above.  If you fundamentally disagree with enabling configurability for the security group, I understand.  Just say so and I will withdraw the PR.

**Comment by joshuamkite** [comment]
Thank you for coming back to me Stephen. I apologise in turn for my delay in responding.

Thanks for explaining your rationale. I do like giving people options here that they can use **if** they want. I can sort of understand why it might seem frustrating to have 'duplicate' security groups. I would ask though what the actual cost is, against the benefit of your proposal. The scenario you describe with dependencies is what I would have expected. Yes, the `depends` you describe could work -if tested in every scenario to verify that- but really they are a construct intended to address API provider deficiencies rather than a first class feature to be used by preference. If you look at the [AWS Security Group limits](https://docs.aws.amazon.com/vpc/latest/userguide/amazon-vpc-limits.html#vpc-limits-security-groups) You will see that the limit for VPC security groups per Region (default = 2500) is very much greater than that for Inbound or outbound rules per security group (60). I won't go into hard and soft limits here, but if deployed across 3 Availability Zones with all features enabled then this bastion module will set 6 security group rules. That's 10% of your 'super' security group's capacity. Unless I am missing something, such as some other benefit,  then I don't think that this a trade-off worth making: For the sake of having a single security group, we introduce much tighter limitations, for both this and other services, with no obvious gain, at the cost of more complicated and contrived dependencies.

**Comment by sacarr** [comment]
Hi Joshua,
I understand your concern.  This is useful for me so I will maintain the code in my personal fork and close the pull request.  Thanks for creating such a useful module.
Stephen

**Comment by joshuamkite** [comment]
Sorry to disappoint you and thanks for the compliment. The module is MIT licenced so there's nothing stopping you forking your own version
Best
Joshua

**Pull request closed without merging**
